[[project]]
path = ""
version = "0.10.0"
assembler = "nasm"
instruction_set = "x86"

[project.opts]
compiler = "nasm"
compile_flags_txt = [
    "-f",
    "-elf",
    "-g",
    "-F",
    "DWARF",
]
diagnostics = true
default_diagnostics = true
